In [1]:
from glob import glob
import pandas as pd
from tqdm import tqdm

from locations import extract_url_map
from events import parse_mmd_taxonomy, extract_events
from timespan import parse_timespan

In [2]:
root_path = "../data/schede mappatura/"

skip = {
    # "david_ruth_FEGB_E_00007": {"rows": 6, "cols": 1}
    "stern_IS_S_00142": {"rows": 2, "cols": 0},
}

In [3]:
chrono_schede = glob(f"{root_path}*/chronotop*")
chrono_schede

['../data/schede mappatura/bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx',
 '../data/schede mappatura/david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx',
 '../data/schede mappatura/bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx',
 '../data/schede mappatura/bruenn_ charlotte_IS_S_00027/chronotopoi_charlotte_bruenn_IS_S_00027 (bozza).xlsx',
 '../data/schede mappatura/0_template/chronotopoi_template.xlsx',
 '../data/schede mappatura/stern_IS_S_00142/chronotopoi_josef_stern_familie_v3.xlsx',
 '../data/schede mappatura/stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx']

## A list of individual sources for experimentation

ignored in the oveall logic

In [4]:
# current = "bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx"
# current = "david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx"
# current = "bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx"
# current = "stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx"
current = "stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx"

chrono_schede = [s for s in chrono_schede if current in s]
chrono_schede

['../data/schede mappatura/stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx']

import openpyxl

overview = {}
for s in chrono_schede:
    wb = openpyxl.load_workbook(s)
    overview[s] = wb.sheetnames
overview

After identification of all sources

# Shortlist processable sources

In [5]:
overview = {
    "stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx": [
        "Josef Stern",
    ],
}

## Put all data together

In [6]:
first = True
df_list = []
for k, v in overview.items():
    for s in v:
        name = k.split("/")[0]
        # print(k,s)
        if name in skip:
            df = pd.read_excel(
                root_path + k, sheet_name=s, skiprows=skip[name]["rows"]
            ).iloc[:, skip[name]["cols"] :]
        else:
            df = pd.read_excel(root_path + k, sheet_name=s)

        print(k, s, df.columns)
        df.columns = [
            "event_label",
            "event_type",
            "place_name",
            "place_type",
            "place_category",
            "wikidata_qid",
            "geonames_id",
            "google maps",
            "date_certainty",
            "date_label",
            "memorial_inscription",
            "source_doc",
            "source_timecode",
            "source_quote",
            "external_links",
            "notes",
        ]

        # merge columns 6+ to notes
        df["notes"] = df[["notes"] + list(df.columns[6:])].apply(
            lambda row: " ".join(row.dropna().astype(str)), axis=1
        )
        # df = df.drop(df.columns[6:], axis=1)

        df["protagonist"] = name
        df["name"] = s
        df_list += [df]
df = pd.concat(df_list, axis=0).astype(str)
df.fillna("", inplace=True)
df

stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx Josef Stern Index(['event_label', 'event_type', 'place_name', 'place_type',
       'place_category', 'wikidata_qid', 'geonames_id', 'google maps',
       'date_certainty', 'date_label', 'memorial_inscription', 'source_doc',
       'source_timecode', 'source_quote', 'external_links', 'notes'],
      dtype='str')

,event_label,event_type,place_name,place_type,place_category,wikidata_qid,geonames_id,google maps,date_certainty,date_label,memorial_inscription,source_doc,source_timecode,source_quote,external_links,notes,protagonist,name
0,Alte Heimat Geburt,birth,"Gießen, Marktplatz 11",,alte_heimat,Q564579,2920512.0,,certain,15/06/1921,,,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 certain 15/06/1921 https://www.geona...,stern_IS_S_00142,Josef Stern
1,Alte Heimat Grundschule,education,Gießen,,alte_heimat,,,,probable,1928-1932,,,,,,probable 1928-1932,stern_IS_S_00142,Josef Stern
2,Alte Heimat Realgymnasium,education,Gießen,,alte_heimat,,,,uncertain,1932- Winter 1935,,,,,,uncertain 1932- Winter 1935,stern_IS_S_00142,Josef Stern
3,Wohnort,residence,Löberstraße 20,,alte_heimat,,,,uncertain,1933?,,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,stern_IS_S_00142,Josef Stern
4,Abgang von der Schule,education,Gießen,,alte_heimat,,,,probable,1935,,,29min 04,,,probable 1935 29min 04,stern_IS_S_00142,Josef Stern
5,Wohnort,residence,"Ghettohaus, Walltorstraße 48",Ghettohaus,alte_heimat,,,,probable,ab 1935,,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,probable ab 1935 https://www.giessen.de/index....,stern_IS_S_00142,Josef Stern
6,Hachschara,education,Schlesien,,alte_heimat,,,,probable,1935,,,30min 57s,,,probable 1935 30min 57s,stern_IS_S_00142,Josef Stern
7,Bei Verwandten,residence,Berlin,,alte_heimat,Q64,2950159.0,,probable,1935,,,31min 31s,,https://www.wikidata.org/wiki/Q64\nhttps://www...,2950159.0 probable 1935 31min 31s https://www....,stern_IS_S_00142,Josef Stern
8,Jeschiwa,education,"Synagoge am Börneplatz, Frankfurt/M",Synagoge,alte_heimat,Q111620976,6553153.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q111620976\nhttp...,31min 58s — [Hinweis: Zerstört im Novemberpogr...,stern_IS_S_00142,Josef Stern
9,Abfahrt > Abschied von den Eltern,farewell,"Bahnhof, Frankfurt am Main",Bahnhof,alte_heimat,Q1794,6553153.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern
10,Auswanderung,emigration_transit,Frankfurt (Main) Hauptbahnhof,Zug,verkehrsmittel,Q165368,6290300.0,,probable,1936,,,32min 16s,,https://www.wikidata.org/wiki/Q165368\nhttps:/...,6290300.0 probable 1936 32min 16s https://www....,stern_IS_S_00142,Josef Stern
11,Auswanderung,emigration_transit,Kehl am Rhein,Zug,verkehrsmittel,Q15979,2891951.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q15979\nhttps://...,2891951.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern
12,Auswanderung,emigration_transit,Brücke Kehl–Straßburg (Rheinquerung),Zug,verkehrsmittel,Q1375288,,,probable,1936,,,,,https://www.wikidata.org/wiki/Q1375288,Heutige Europabrücke ab 1960; 1936 nutzte Ster...,stern_IS_S_00142,Josef Stern
13,Auswanderung,emigration_transit,Marseille,Zug,verkehrsmittel,Q23482,2995469.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q23482\nhttps://...,2995469.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern
14,Auswanderung,emigration,Marseille,Schiff,verkehrsmittel,,,,probable,1936,,,,,,probable 1936,stern_IS_S_00142,Josef Stern
15,Neue Heimat\nEinwanderung,immigration,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",,neue_heimat,,,,probable,1936-38,,,,,,probable 1936-38,stern_IS_S_00142,Josef Stern
16,Neue Heimat\n\nReise durchs Land,residence,Ēmeq Yizrəʿēl,,neue_heimat,Q763829,293165.0,,probable,1937,,,,,https://www.wikidata.org/wiki/Q763829\nhttps:/...,Jesreelebene 293165.0 probable 1937 https://ww...,stern_IS_S_00142,Josef Stern
17,Neue Heimat,residence,Kibbuz Ein HaNetziv,,neue_heimat,Q2095906,295211.0,,uncertain,1938-194?,,,,,https://www.wikidata.org/wiki/Q2095906\nhttps:...,aus dem Kibbuz ausgewiesen 295211.0 uncertain ...,stern_IS_S_00142,Josef Stern
18,Neue Heimat,residence,Haifa,,neue_heimat,Q41621,294801.0,,uncertain,194?–,,,,,https://www.geonames.org/294801/haifa.html\nht...,Fabrik in der Nähe von Haifa 294801.0 uncertai...,stern_IS_S_00142,Josef Stern
19,Neue Heimat,residence,Kibbuz Tirat Tsvi,,neue_heimat,Q550025,293304.0,,uncertain,1940-1944,,,,,https://www.wikidata.org/wiki/Q550025\nhttps:/...,293304.0 uncertain 1940-1944 https://www.wikid...,stern_IS_S_00142,Josef Stern
20,Reise zurück als Soldat,military_service,Italien,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern
21,Reise zurück als Soldat,military_service,Deutschland,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern
22,Reise zurück als Soldat,military_service,Belgien,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern
23,Reise zurück als Soldat,military_service,Niederlande,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern
24,Neue Heimat\nHeirat,marriage,Haifa,,neue_heimat,,,,uncertain,,,,,,,uncertain,stern_IS_S_00142,Josef Stern
25,Neue Heimat\nHaifa\nBeruf,work,"Haifa, Universität, Bibliothek",,neue_heimat,,,,probable,1966–1986,,,,,,probable 1966–1986,stern_IS_S_00142,Josef Stern
26,Reise zurück,return_visit_transit,Gießen,,reise_zurueck,Q564579,2920512.0,,probable,1975,,,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 probable 1975 https://www.geonames.o...,stern_IS_S_00142,Josef Stern
27,Fahrt Frankfurt-Gießen,return_visit_transit,Frankfurt am Main,Zug,reise_zurueck,Q1794,6553153.0,,,,,,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 https://www.wikidata.org/wiki/Q1794\...,stern_IS_S_00142,Josef Stern
28,Klein Linden,return_visit_transit,Klein-Linden,Zug,reise_zurueck,Q1571834,2888549.0,,,,,,,,https://www.wikidata.org/wiki/Q1571834\nhttps:...,2888549.0 https://www.wikidata.org/wiki/Q15718...,stern_IS_S_00142,Josef Stern
29,Großen-Linden,return_visit,Großen-Linden,Zug,reise_zurueck,Q116016915,11974166.0,,,,,,,,https://www.wikidata.org/wiki/Q116016915\nhttp...,11974166.0 https://www.wikidata.org/wiki/Q1160...,stern_IS_S_00142,Josef Stern
30,Geburtshaus Marktplatz 11,return_visit_transit,"Marktplatz 11, Giessen",Zug,reise_zurueck,,,,,,,,,,,Geburtshaus Geburtshaus,stern_IS_S_00142,Josef Stern
31,Aliyah-Anruf,notification,"Gießen, Walltorstraße 48",Telephon im Ghettohaus,alte_heimat,Q564579,2920512.0,,probable,1936,,Interview Metz 2010,30min 15s,"Ich bekam einen Anruf am Telefon in dem Haus, ...",,Chronotopos im engeren Sinn: Ort (Walltorstraß...,stern_IS_S_00142,Josef Stern
32,Zwangsausweisung Marktplatz 11,forced_eviction,"Gießen, Marktplatz 11",,ort_der_zeit,Q564579,2920512.0,,probable,1933,,Interview Metz 2010,11min 47s,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,stern_IS_S_00142,Josef Stern

# Locations

In [7]:
# locs = {n:l for l, n in df["location"].apply(lambda x: extract_urls(x)).to_list()}
locs = {}
for row in tqdm(df.to_dict(orient="records")):
    # print(row)
    # print(extract_urls(row))
    name = row["place_name"]
    locs[name] = {}
    place_labels = set()
    if "place_type" in row and row["place_type"].strip():
        place_labels |= {row["place_type"].strip()}
    if row["place_category"].strip():
        place_labels |= {row["place_category"].strip()}
    locs[name]["label"] = ",".join(place_labels)

    urls = extract_url_map(row["external_links"])
    if (
        "www.wikidata.org" not in urls
        and "wikidata_id" in row
        and row["wikidata_qid"].strip()
    ):
        locs[name]["www.wikidata.org"] = (
            "https://www.wikidata.org/wiki/" + row["wikidata_qid"].strip()
        )
    if (
        "www.geonames.org" not in urls
        and "geonames_id" in row
        and row["geonames_id"].strip()
    ):
        locs[name]["www.geonames.org"] = (
            "https://www.geonames.org/" + row["geonames_id"].strip()
        )

    locs[name].update(urls[0])
print(locs)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:00<00:00, 16815.94it/s]

{'Gießen, Marktplatz 11': {'label': 'ort_der_zeit', 'www.geonames.org': 'https://www.geonames.org/2920512.0'}, 'Gießen': {'label': 'reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/2920512/giessen.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q564579'}, 'Löberstraße 20': {'label': 'alte_heimat', 'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1'}, 'Ghettohaus, Walltorstraße 48': {'label': 'alte_heimat,Ghettohaus', 'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1'}, 'Schlesien': {'label': 'alte_heimat'}, 'Berlin': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2950159/berlin.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q64'}, 'Synagoge am Börneplatz, Frankfurt/M': {'label': 'alte_heimat,Synagoge', 'www.geonames.org': 'https://www.geonames.org/6553153/frankfurt-am-main.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794'}, 'Bahnhof, Frankfurt am Main': {'label': 'alte_heimat,Bahnhof', 'www.geonames.org': 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794'}, 'Frankfurt (Main) Hauptbahnhof': {'label': 'verkehrsmittel,Zug', 'www.geonames.org': 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q165368'}, 'Kehl am Rhein': {'label': 'verkehrsmittel,Zug', 'www.geonames.org': 'https://www.geonames.org/2891951/kehl.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q15979'}, 'Brücke Kehl–Straßburg (Rheinquerung)': {'label': 'verkehrsmittel,Zug', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1375288'}, 'Marseille': {'label': 'verkehrsmittel,Schiff'}, 'Kibbuz Rodges, besteht nicht mehr (in der Nähe von Petah Tikva)': {'label': 'neue_heimat'}, 'Ēmeq Yizrəʿēl': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/293165/jezreel-valley.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q763829'}, 'Kibbuz Ein HaNetziv': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/295211/-en-hanaziv.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2095906'}, 'Haifa': {'label': 'neue_heimat'}, 'Kibbuz Tirat Tsvi': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/293304/tirat-tsvi.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q550025'}, 'Italien': {'label': 'reise_zurueck'}, 'Deutschland': {'label': 'reise_zurueck'}, 'Belgien': {'label': 'reise_zurueck'}, 'Niederlande': {'label': 'reise_zurueck'}, 'Haifa, Universität, Bibliothek': {'label': 'neue_heimat'}, 'Frankfurt am Main': {'label': 'Zug,reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/6553153/frankfurt-am-main.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794'}, 'Klein-Linden': {'label': 'Zug,reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/2888549/klein-linden.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1571834'}, 'Großen-Linden': {'label': 'Zug,reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/11974166/grossen-linden.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q116016915'}, 'Marktplatz 11, Giessen': {'label': 'Zug,reise_zurueck'}, 'Gießen, Walltorstraße 48': {'label': 'Telephon im Ghettohaus,alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2920512.0'}}

## Update preexisting locations

In [8]:
rich = pd.read_excel("locations.xlsx", dtype=str)
rich = rich.set_index(["location"])

for location, row in locs.items():
    if location not in rich.index:
        rich.loc[location] = locs[location]

    # Add any new columns from locs that don't exist yet
    for col, val in row.items() if isinstance(row, dict) else {}:
        if col not in rich.columns:
            rich[col] = ""
        rich.loc[location, col] = str(val)

rich.to_excel("locations.xlsx")

# Events

TODO: incomplete due to too much noise. Issues:

- use LL or Lebenslauf, currently extracted as one, but need to be two equivalent
- "alter heimant" instread of "alte heimat"
- "Transport", "Tod des Vaters",  are not label

In [9]:
event_taxonomy = parse_mmd_taxonomy("../model/tassonomia.mmd")
events = sorted(set(event_taxonomy.keys()), key=lambda x: -len(x))
len(events), events[:5] + ["..."] + events[-5:]

(340,
 ['Città/regioni tedesche, austriache, ceche',
  'SR – Spazi sociali / istituzioni',
  'Friedrichswerdersche Gymnasium',
  'Europa – altri paesi e luoghi',
  'Berlino – quartieri e luoghi',
  '...',
  'Zug',
  'SPD',
  'USA',
  'KPD',
  'Tod'])

In [10]:
df["event"] = df["event_label"].apply(lambda x: extract_events(x, events))
df

,event_label,event_type,place_name,place_type,place_category,wikidata_qid,geonames_id,google maps,date_certainty,date_label,memorial_inscription,source_doc,source_timecode,source_quote,external_links,notes,protagonist,name,event
0,Alte Heimat Geburt,birth,"Gießen, Marktplatz 11",,alte_heimat,Q564579,2920512.0,,certain,15/06/1921,,,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 certain 15/06/1921 https://www.geona...,stern_IS_S_00142,Josef Stern,"[alte Heimat, Geburt]"
1,Alte Heimat Grundschule,education,Gießen,,alte_heimat,,,,probable,1928-1932,,,,,,probable 1928-1932,stern_IS_S_00142,Josef Stern,"[alte Heimat, Grundschule]"
2,Alte Heimat Realgymnasium,education,Gießen,,alte_heimat,,,,uncertain,1932- Winter 1935,,,,,,uncertain 1932- Winter 1935,stern_IS_S_00142,Josef Stern,"[Realgymnasium, alte Heimat]"
3,Wohnort,residence,Löberstraße 20,,alte_heimat,,,,uncertain,1933?,,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,stern_IS_S_00142,Josef Stern,[Wohnort]
4,Abgang von der Schule,education,Gießen,,alte_heimat,,,,probable,1935,,,29min 04,,,probable 1935 29min 04,stern_IS_S_00142,Josef Stern,[Abgang von der Schule]
5,Wohnort,residence,"Ghettohaus, Walltorstraße 48",Ghettohaus,alte_heimat,,,,probable,ab 1935,,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,probable ab 1935 https://www.giessen.de/index....,stern_IS_S_00142,Josef Stern,[Wohnort]
6,Hachschara,education,Schlesien,,alte_heimat,,,,probable,1935,,,30min 57s,,,probable 1935 30min 57s,stern_IS_S_00142,Josef Stern,[Hachschara]
7,Bei Verwandten,residence,Berlin,,alte_heimat,Q64,2950159.0,,probable,1935,,,31min 31s,,https://www.wikidata.org/wiki/Q64\nhttps://www...,2950159.0 probable 1935 31min 31s https://www....,stern_IS_S_00142,Josef Stern,"[Verwandte, Bei n]"
8,Jeschiwa,education,"Synagoge am Börneplatz, Frankfurt/M",Synagoge,alte_heimat,Q111620976,6553153.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q111620976\nhttp...,31min 58s — [Hinweis: Zerstört im Novemberpogr...,stern_IS_S_00142,Josef Stern,[Jeschiwa]
9,Abfahrt > Abschied von den Eltern,farewell,"Bahnhof, Frankfurt am Main",Bahnhof,alte_heimat,Q1794,6553153.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,"[Abschied von den Eltern, Abfahrt, >]"
10,Auswanderung,emigration_transit,Frankfurt (Main) Hauptbahnhof,Zug,verkehrsmittel,Q165368,6290300.0,,probable,1936,,,32min 16s,,https://www.wikidata.org/wiki/Q165368\nhttps:/...,6290300.0 probable 1936 32min 16s https://www....,stern_IS_S_00142,Josef Stern,[Auswanderung]
11,Auswanderung,emigration_transit,Kehl am Rhein,Zug,verkehrsmittel,Q15979,2891951.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q15979\nhttps://...,2891951.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,[Auswanderung]
12,Auswanderung,emigration_transit,Brücke Kehl–Straßburg (Rheinquerung),Zug,verkehrsmittel,Q1375288,,,probable,1936,,,,,https://www.wikidata.org/wiki/Q1375288,Heutige Europabrücke ab 1960; 1936 nutzte Ster...,stern_IS_S_00142,Josef Stern,[Auswanderung]
13,Auswanderung,emigration_transit,Marseille,Zug,verkehrsmittel,Q23482,2995469.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q23482\nhttps://...,2995469.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,[Auswanderung]
14,Auswanderung,emigration,Marseille,Schiff,verkehrsmittel,,,,probable,1936,,,,,,probable 1936,stern_IS_S_00142,Josef Stern,[Auswanderung]
15,Neue Heimat\nEinwanderung,immigration,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",,neue_heimat,,,,probable,1936-38,,,,,,probable 1936-38,stern_IS_S_00142,Josef Stern,"[neue Heimat, Einwanderung]"
16,Neue Heimat\n\nReise durchs Land,residence,Ēmeq Yizrəʿēl,,neue_heimat,Q763829,293165.0,,probable,1937,,,,,https://www.wikidata.org/wiki/Q763829\nhttps:/...,Jesreelebene 293165.0 probable 1937 https://ww...,stern_IS_S_00142,Josef Stern,"[Reise durchs Land, neue Heimat]"
17,Neue Heimat,residence,Kibbuz Ein HaNetziv,,neue_heimat,Q2095906,295211.0,,uncertain,1938-194?,,,,,https://www.wikidata.org/wiki/Q2095906\nhttps:...,aus dem Kibbuz ausgewiesen 295211.0 uncertain ...,stern_IS_S_00142,Josef Stern,[neue Heimat]
18,Neue Heimat,residence,Haifa,,neue_heimat,Q41621,294801.0,,uncertain,194?–,,,,,https://www.geonames.org/294801/haifa.html\nht...,Fabrik in der Nähe von Haifa 294801.0 uncertai...,stern_IS_S_00142,Josef Stern,[neue Heimat]
19,Neue Heimat,residence,Kibbuz Tirat Tsvi,,neue_heimat,Q550025,293304.0,,uncertain,1940-1944,,,,,https://www.wikidata.org/wiki/Q550025\nhttps:/...,293304.0 uncertain 1940-1944 https://www.wikid...,stern_IS_S_00142,Josef Stern,[neue Heimat]
20,Reise zurück als Soldat,military_service,Italien,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern,"[Reise zurück, als Soldat]"
21,Reise zurück als Soldat,military_service,Deutschland,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern,"[Reise zurück, als Soldat]"
22,Reise zurück als Soldat,military_service,Belgien,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern,"[Reise zurück, als Soldat]"
23,Reise zurück als Soldat,military_service,Niederlande,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern,"[Reise zurück, als Soldat]"
24,Neue Heimat\nHeirat,marriage,Haifa,,neue_heimat,,,,uncertain,,,,,,,uncertain,stern_IS_S_00142,Josef Stern,"[neue Heimat, Heirat]"
25,Neue Heimat\nHaifa\nBeruf,work,"Haifa, Universität, Bibliothek",,neue_heimat,,,,probable,1966–1986,,,,,,probable 1966–1986,stern_IS_S_00142,Josef Stern,"[neue Heimat, Beruf, Haifa]"
26,Reise zurück,return_visit_transit,Gießen,,reise_zurueck,Q564579,2920512.0,,probable,1975,,,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 probable 1975 https://www.geonames.o...,stern_IS_S_00142,Josef Stern,[Reise zurück]
27,Fahrt Frankfurt-Gießen,return_visit_transit,Frankfurt am Main,Zug,reise_zurueck,Q1794,6553153.0,,,,,,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 https://www.wikidata.org/wiki/Q1794\...,stern_IS_S_00142,Josef Stern,"[Gießen, Fahrt Frankfurt-]"
28,Klein Linden,return_visit_transit,Klein-Linden,Zug,reise_zurueck,Q1571834,2888549.0,,,,,,,,https://www.wikidata.org/wiki/Q1571834\nhttps:...,2888549.0 https://www.wikidata.org/wiki/Q15718...,stern_IS_S_00142,Josef Stern,[Klein Linden]
29,Großen-Linden,return_visit,Großen-Linden,Zug,reise_zurueck,Q116016915,11974166.0,,,,,,,,https://www.wikidata.org/wiki/Q116016915\nhttp...,11974166.0 https://www.wikidata.org/wiki/Q1160...,stern_IS_S_00142,Josef Stern,[Großen-Linden]
30,Geburtshaus Marktplatz 11,return_visit_transit,"Marktplatz 11, Giessen",Zug,reise_zurueck,,,,,,,,,,,Geburtshaus Geburtshaus,stern_IS_S_00142,Josef Stern,"[Geburtshaus, Marktplatz 11]"
31,Aliyah-Anruf,notification,"Gießen, Walltorstraße 48",Telephon im Ghettohaus,alte_heimat,Q564579,2920512.0,,probable,1936,,Interview Metz 2010,30min 15s,"Ich bekam einen Anruf am Telefon in dem Haus, ...",,Chronotopos im engeren Sinn: Ort (Walltorstraß...,stern_IS_S_00142,Josef Stern,[Aliyah-Anruf]
32,Zwangsausweisung Marktplatz 11,forced_eviction,"Gießen, Marktplatz 11",,ort_der_zeit,Q564579,2920512.0,,probable,1933,,Interview Metz 2010,11min 47s,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,stern_IS_S_00142,Josef Stern,[Zwangsausweisung Marktplatz 11]

# Timespan

In [11]:
df[["time_start", "time_end"]] = (
    df["date_label"].apply(lambda ts: list(parse_timespan(ts).as_tuple())).tolist()
)
df

,event_label,event_type,place_name,place_type,place_category,wikidata_qid,geonames_id,google maps,date_certainty,date_label,...,source_doc,source_timecode,source_quote,external_links,notes,protagonist,name,event,time_start,time_end
0,Alte Heimat Geburt,birth,"Gießen, Marktplatz 11",,alte_heimat,Q564579,2920512.0,,certain,15/06/1921,...,,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 certain 15/06/1921 https://www.geona...,stern_IS_S_00142,Josef Stern,"[alte Heimat, Geburt]",1921-06-15,1921-06-15
1,Alte Heimat Grundschule,education,Gießen,,alte_heimat,,,,probable,1928-1932,...,,,,,probable 1928-1932,stern_IS_S_00142,Josef Stern,"[alte Heimat, Grundschule]",1928-01-01,1932-12-31
2,Alte Heimat Realgymnasium,education,Gießen,,alte_heimat,,,,uncertain,1932- Winter 1935,...,,,,,uncertain 1932- Winter 1935,stern_IS_S_00142,Josef Stern,"[Realgymnasium, alte Heimat]",1932-01-01,1932-12-31
3,Wohnort,residence,Löberstraße 20,,alte_heimat,,,,uncertain,1933?,...,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,stern_IS_S_00142,Josef Stern,[Wohnort],1933-01-01,1933-12-31
4,Abgang von der Schule,education,Gießen,,alte_heimat,,,,probable,1935,...,,29min 04,,,probable 1935 29min 04,stern_IS_S_00142,Josef Stern,[Abgang von der Schule],1935-01-01,1935-12-31
5,Wohnort,residence,"Ghettohaus, Walltorstraße 48",Ghettohaus,alte_heimat,,,,probable,ab 1935,...,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,probable ab 1935 https://www.giessen.de/index....,stern_IS_S_00142,Josef Stern,[Wohnort],1935-01-01,1935-12-31
6,Hachschara,education,Schlesien,,alte_heimat,,,,probable,1935,...,,30min 57s,,,probable 1935 30min 57s,stern_IS_S_00142,Josef Stern,[Hachschara],1935-01-01,1935-12-31
7,Bei Verwandten,residence,Berlin,,alte_heimat,Q64,2950159.0,,probable,1935,...,,31min 31s,,https://www.wikidata.org/wiki/Q64\nhttps://www...,2950159.0 probable 1935 31min 31s https://www....,stern_IS_S_00142,Josef Stern,"[Verwandte, Bei n]",1935-01-01,1935-12-31
8,Jeschiwa,education,"Synagoge am Börneplatz, Frankfurt/M",Synagoge,alte_heimat,Q111620976,6553153.0,,probable,1936,...,,,,https://www.wikidata.org/wiki/Q111620976\nhttp...,31min 58s — [Hinweis: Zerstört im Novemberpogr...,stern_IS_S_00142,Josef Stern,[Jeschiwa],1936-01-01,1936-12-31
9,Abfahrt > Abschied von den Eltern,farewell,"Bahnhof, Frankfurt am Main",Bahnhof,alte_heimat,Q1794,6553153.0,,probable,1936,...,,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,"[Abschied von den Eltern, Abfahrt, >]",1936-01-01,1936-12-31
10,Auswanderung,emigration_transit,Frankfurt (Main) Hauptbahnhof,Zug,verkehrsmittel,Q165368,6290300.0,,probable,1936,...,,32min 16s,,https://www.wikidata.org/wiki/Q165368\nhttps:/...,6290300.0 probable 1936 32min 16s https://www....,stern_IS_S_00142,Josef Stern,[Auswanderung],1936-01-01,1936-12-31
11,Auswanderung,emigration_transit,Kehl am Rhein,Zug,verkehrsmittel,Q15979,2891951.0,,probable,1936,...,,,,https://www.wikidata.org/wiki/Q15979\nhttps://...,2891951.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,[Auswanderung],1936-01-01,1936-12-31
12,Auswanderung,emigration_transit,Brücke Kehl–Straßburg (Rheinquerung),Zug,verkehrsmittel,Q1375288,,,probable,1936,...,,,,https://www.wikidata.org/wiki/Q1375288,Heutige Europabrücke ab 1960; 1936 nutzte Ster...,stern_IS_S_00142,Josef Stern,[Auswanderung],1936-01-01,1936-12-31
13,Auswanderung,emigration_transit,Marseille,Zug,verkehrsmittel,Q23482,2995469.0,,probable,1936,...,,,,https://www.wikidata.org/wiki/Q23482\nhttps://...,2995469.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,[Auswanderung],1936-01-01,1936-12-31
14,Auswanderung,emigration,Marseille,Schiff,verkehrsmittel,,,,probable,1936,...,,,,,probable 1936,stern_IS_S_00142,Josef Stern,[Auswanderung],1936-01-01,1936-12-31
15,Neue Heimat\nEinwanderung,immigration,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",,neue_heimat,,,,probable,1936-38,...,,,,,probable 1936-38,stern_IS_S_00142,Josef Stern,"[neue Heimat, Einwanderung]",1936-01-01,1938-12-31
16,Neue Heimat\n\nReise durchs Land,residence,Ēmeq Yizrəʿēl,,neue_heimat,Q763829,293165.0,,probable,1937,...,,,,https://www.wikidata.org/wiki/Q763829\nhttps:/...,Jesreelebene 293165.0 probable 1937 https://ww...,stern_IS_S_00142,Josef Stern,"[Reise durchs Land, neue Heimat]",1937-01-01,1937-12-31
17,Neue Heimat,residence,Kibbuz Ein HaNetziv,,neue_heimat,Q2095906,295211.0,,uncertain,1938-194?,...,,,,https://www.wikidata.org/wiki/Q2095906\nhttps:...,aus dem Kibbuz ausgewiesen 295211.0 uncertain ...,stern_IS_S_00142,Josef Stern,[neue Heimat],1938-01-01,1949-12-31
18,Neue Heimat,residence,Haifa,,neue_heimat,Q41621,294801.0,,uncertain,194?–,...,,,,https://www.geonames.org/294801/haifa.html\nht...,Fabrik in der Nähe von Haifa 294801.0 uncertai...,stern_IS_S_00142,Josef Stern,[neue Heimat],1940-01-01,1949-12-31
19,Neue Heimat,residence,Kibbuz Tirat Tsvi,,neue_heimat,Q550025,293304.0,,uncertain,1940-1944,...,,,,https://www.wikidata.org/wiki/Q550025\nhttps:/...,293304.0 uncertain 1940-1944 https://www.wikid...,stern_IS_S_00142,Josef Stern,[neue Heimat],1940-01-01,1944-12-31
20,Reise zurück als Soldat,military_service,Italien,,reise_zurueck,,,,probable,1944,...,,,,,probable 1944,stern_IS_S_00142,Josef Stern,"[Reise zurück, als Soldat]",1944-01-01,1944-12-31
21,Reise zurück als Soldat,military_service,Deutschland,,reise_zurueck,,,,probable,1944,...,,,,,probable 1944,stern_IS_S_00142,Josef Stern,"[Reise zurück, als Soldat]",1944-01-01,1944-12-31
22,Reise zurück als Soldat,military_service,Belgien,,reise_zurueck,,,,probable,1944,...,,,,,probable 1944,stern_IS_S_00142,Josef Stern,"[Reise zurück, als Soldat]",1944-01-01,1944-12-31
23,Reise zurück als Soldat,military_service,Niederlande,,reise_zurueck,,,,probable,1944,...,,,,,probable 1944,stern_IS_S_00142,Josef Stern,"[Reise zurück, als Soldat]",1944-01-01,1944-12-31
24,Neue Heimat\nHeirat,marriage,Haifa,,neue_heimat,,,,uncertain,,...,,,,,uncertain,stern_IS_S_00142,Josef Stern,"[neue Heimat, Heirat]",None,None
25,Neue Heimat\nHaifa\nBeruf,work,"Haifa, Universität, Bibliothek",,neue_heimat,,,,probable,1966–1986,...,,,,,probable 1966–1986,stern_IS_S_00142,Josef Stern,"[neue Heimat, Beruf, Haifa]",1966-01-01,1986-12-31
26,Reise zurück,return_visit_transit,Gießen,,reise_zurueck,Q564579,2920512.0,,probable,1975,...,,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 probable 1975 https://www.geonames.o...,stern_IS_S_00142,Josef Stern,[Reise zurück],1975-01-01,1975-12-31
27,Fahrt Frankfurt-Gießen,return_visit_transit,Frankfurt am Main,Zug,reise_zurueck,Q1794,6553153.0,,,,...,,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 https://www.wikidata.org/wiki/Q1794\...,stern_IS_S_00142,Josef Stern,"[Gießen, Fahrt Frankfurt-]",None,None
28,Klein Linden,return_visit_transit,Klein-Linden,Zug,reise_zurueck,Q1571834,2888549.0,,,,...,,,,https://www.wikidata.org/wiki/Q1571834\nhttps:...,2888549.0 https://www.wikidata.org/wiki/Q15718...,stern_IS_S_00142,Josef Stern,[Klein Linden],None,None
29,Großen-Linden,return_visit,Großen-Linden,Zug,reise_zurueck,Q116016915,11974166.0,,,,...,,,,https://www.wikidata.org/wiki/Q116016915\nhttp...,11974166.0 https://www.wikidata.org/wiki/Q1160...,stern_IS_S_00142,Josef Stern,[Großen-Linden],None,None
30,Geburtshaus Marktplatz 11,return_visit_transit,"Marktplatz 11, Giessen",Zug,reise_zurueck,,,,,,...,,,,,Geburtshaus Geburtshaus,stern_IS_S_00142,Josef Stern,"[Geburtshaus, Marktplatz 11]",None,None
31,Aliyah-Anruf,notification,"Gießen, Walltorstraße 48",Telephon im Ghettohaus,alte_heimat,Q564579,2920512.0,,probable,1936,...,Interview Metz 2010,30min 15s,"Ich bekam einen Anruf am Telefon in dem Haus, ...",,Chronotopos im engeren Sinn: Ort (Walltorstraß...,stern_IS_S_00142,Josef Stern,[Aliyah-Anruf],1936-01-01,1936-12-31
32,Zwangsausweisung Marktplatz 11,forced_eviction,"Gießen, Marktplatz 11",,ort_der_zeit,Q564579,2920512.0,,probable,1933,...,Interview Metz 2010,11min 47s,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,stern_IS_S_00142,Josef Stern,[Zwangsausweisung Marktplatz 11],1933-01-01,1933-12-31

# Notes

left unprocessed for now

In [12]:
set(df["notes"])

{'11974166.0 https://www.wikidata.org/wiki/Q116016915\nhttps://www.geonames.org/11974166/grossen-linden.html',
 '2888549.0 https://www.wikidata.org/wiki/Q1571834\nhttps://www.geonames.org/2888549/klein-linden.html',
 '2891951.0 probable 1936 https://www.wikidata.org/wiki/Q15979\nhttps://www.geonames.org/2891951/kehl.html',
 '2920512.0 certain 15/06/1921 https://www.geonames.org/2920512/giessen.html\nhttps://www.wikidata.org/wiki/Q564579\nhttps://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1',
 '2920512.0 probable 1975 https://www.geonames.org/2920512/giessen.html\nhttps://www.wikidata.org/wiki/Q564579',
 '293304.0 uncertain 1940-1944 https://www.wikidata.org/wiki/Q550025\nhttps://www.geonames.org/293304/tirat-tsvi.html',
 '2950159.0 probable 1935 31min 31s https://www.wikidata.org/wiki/Q64\nhttps://www.geonames.org/2950159/berlin.html',
 '2995469.0 probable 1936 https://www.wikidata.org/wiki/Q23482\nhttps://www.geonames.org/2995469/marseille.html',
 '31min 58s — [Hinweis: Zerstört im Novemberpogrom 1938; heute Gedenkstätte Neuer Börneplatz.] 6553153.0 probable 1936 https://www.wikidata.org/wiki/Q111620976\nhttps://www.wikidata.org/wiki/Q1794\nhttps://www.geonames.org/6553153/frankfurt-am-main.html 31min 58s — [Hinweis: Zerstört im Novemberpogrom 1938; heute Gedenkstätte Neuer Börneplatz.]',
 '6290300.0 probable 1936 32min 16s https://www.wikidata.org/wiki/Q165368\nhttps://www.geonames.org/6290300/frankfurt-hauptbahnhof.html',
 '6553153.0 https://www.wikidata.org/wiki/Q1794\nhttps://www.geonames.org/6553153/frankfurt-am-main.html',
 '6553153.0 probable 1936 https://www.wikidata.org/wiki/Q1794\nhttps://www.geonames.org/6553153/frankfurt-am-main.html\nhttps://www.geonames.org/6290300/frankfurt-hauptbahnhof.html',
 "Aufräumung v4: place_name korrigiert von 'Löberstraße 20 11' zu 'Löberstraße 20'. uncertain 1933? https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1 Aufräumung v4: place_name korrigiert von 'Löberstraße 20 11' zu 'Löberstraße 20'.",
 'Chronotopos im engeren Sinn: Ort (Walltorstraße 48), Zeit (zwei-Tage-Ultimatum), Medium (Telephon) und ausgehender Knotenpunkt (Frankfurt Hauptbahnhof) in einem Moment verdichtet. Markiert den Beginn der Aliyah-Bewegung Josefs. 2920512.0 probable 1936 Interview Metz 2010 30min 15s Ich bekam einen Anruf am Telefon in dem Haus, in dem wir später gewohnt haben, was später zum Ghetto-Haus wurde. Ich soll innerhalb zwei Tagen bereit sein, zur Alijah nach Frankfurt zu fahren und den Zug zu nehmen Chronotopos im engeren Sinn: Ort (Walltorstraße 48), Zeit (zwei-Tage-Ultimatum), Medium (Telephon) und ausgehender Knotenpunkt (Frankfurt Hauptbahnhof) in einem Moment verdichtet. Markiert den Beginn der Aliyah-Bewegung Josefs.',
 'Fabrik in der Nähe von Haifa 294801.0 uncertain 194?– https://www.geonames.org/294801/haifa.html\nhttps://www.wikidata.org/wiki/Q41621 Fabrik in der Nähe von Haifa',
 'Geburtshaus  Geburtshaus ',
 'Heutige Europabrücke ab 1960; 1936 nutzte Stern die alte Straßenbrücke von 1897 (1939 zerstört). probable 1936 https://www.wikidata.org/wiki/Q1375288 Heutige Europabrücke ab 1960; 1936 nutzte Stern die alte Straßenbrücke von 1897 (1939 zerstört).',
 'Jesreelebene 293165.0 probable 1937 https://www.wikidata.org/wiki/Q763829\nhttps://www.geonames.org/293165/jezreel-valley.html Jesreelebene',
 'Josef war 12 Jahre alt. Erstes durch ihn erinnertes NS-Verfügungsereignis; familienkollektiv. 2920512.0 probable 1933 Interview Metz 2010 11min 47s Wir sind allerdings aus diesem schönen Haus gleich 1933 ausgewiesen worden, weil es unter Denkmalschutz stand. Und in einem solchen Haus durften Juden nicht leben. Das war eine der allerersten Verfügungen der Nazis in Gießen. Josef war 12 Jahre alt. Erstes durch ihn erinnertes NS-Verfügungsereignis; familienkollektiv.',
 'aus dem Kibbuz ausgewiesen 295211.0 uncertain 1938-194? https://www.wikidata.org/wiki/Q2095906\nhttps://www.geonames.org/295211/-en-hanaziv.html aus dem Kibbuz ausgewiesen',
 'probable 1928-1932',
 'probable 1935 29min 04',
 'probable 1935 30min 57s',
 'probable 1936',
 'probable 1936-38',
 'probable 1944',
 'probable 1966–1986',
 'probable ab 1935 https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1',
 'uncertain',
 'uncertain 1932- Winter 1935'}

# Links

left unprocessed for now

In [16]:
urls = set()
for cell in df["external_links"]:
    if pd.notna(cell):
        for url in str(cell).split("\n"):
            url = url.strip()
            if url:
                urls.add(url)
urls

{'https://www.geonames.org/11974166/grossen-linden.html',
 'https://www.geonames.org/2888549/klein-linden.html',
 'https://www.geonames.org/2891951/kehl.html',
 'https://www.geonames.org/2920512/giessen.html',
 'https://www.geonames.org/293165/jezreel-valley.html',
 'https://www.geonames.org/293304/tirat-tsvi.html',
 'https://www.geonames.org/294801/haifa.html',
 'https://www.geonames.org/2950159/berlin.html',
 'https://www.geonames.org/295211/-en-hanaziv.html',
 'https://www.geonames.org/2995469/marseille.html',
 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html',
 'https://www.geonames.org/6553153/frankfurt-am-main.html',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1',
 'https://www.wikidata.org/wiki/Q111620976',
 'https://www.wikidata.org/wiki/Q116016915',
 'https://www.wikidata.org/wiki/Q1375288',
 'https://www.wikidata.org/wiki/Q1571834',
 'https://www.wikidata.org/wiki/Q15979',
 'https://www.wikidata.org/wiki/Q165368',
 'https://www.wikidata.org/wiki/Q1794',
 'https://www.wikidata.org/wiki/Q2095906',
 'https://www.wikidata.org/wiki/Q23482',
 'https://www.wikidata.org/wiki/Q41621',
 'https://www.wikidata.org/wiki/Q550025',
 'https://www.wikidata.org/wiki/Q564579',
 'https://www.wikidata.org/wiki/Q64',
 'https://www.wikidata.org/wiki/Q763829'}